#!/bin/bash

# Please run this as root or give sudo access for the airmon-ng command
# give sudo access to the current user for these commands:
# airmon-ng, start, stop, nmcli, pkill, service, iwconfig and packet-monitor/main


DEVICE="wlan0"
MON_DEVICE="mon0"
CHANNEL=1
TIME=1
PACKET_MONITOR="packet-monitor/main"

STOP="sudo airmon-ng stop $MON_DEVICE"
START="sudo airmon-ng start $DEVICE > /dev/null 2>&1"
FORCE_STOP="$STOP ; sudo start network-manager"

# disconnect from network and kill services
nmcli d disconnect iface $DEVICE > /dev/null 2>&1
sudo service avahi-daemon stop > /dev/null 2>&1
sudo stop network-manager > /dev/null 2>&1
sudo pkill wpa_supplicant
sudo pkill dhclient

# stop if any error occurs
set -e

# make sure to cleanup mon0 when interrupted
trap '{ $FORCE_STOP ; echo trap ; exit 0; }' SIGINT SIGKILL SIGTERM EXIT

# enable monitor mode for the device
$START > /dev/null 2>&1

while [[ true ]]; do
    for (( CHANNEL = 1; CHANNEL < 12; CHANNEL++ )); do

        # change channel
        echo "#channel $CHANNEL"
        sudo iwconfig $DEVICE channel $CHANNEL
        # sleep 5

        # execute the packet-monitor for a period of time
#        set +e
        # sudo timeout $TIME $PACKET_MONITOR $TIME $CHANNEL
        sudo $PACKET_MONITOR $CHANNEL $TIME
#        set -e


    done
done

# stop monitor mode
$STOP > /dev/null 2>&1

# restore service
sudo start network-manager > /dev/null 2>&1
